name: slr-environment
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas
  - unidecode
  - numpy
  - matplotlib
  - itertools
  - collections
  - sklearn
  - scipy
  - ipywidgets
  - tqdm
  #- community
  - nltk
  - spacy
  - pip
  - pip:
      - nltk
      - spacy
      - networkx
      - scikit-learn
      #- python-louvain